import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/SideNav";
import TopNav from "@/components/TopNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//        <div className="flex min-h-screen">
//           <Sidebar />
//           <main className="flex-1 p-4">{children}</main>
//         </div>
//       </body>
//     </html>
//   );
// }


// import Sidebar from "@/components/SideNav";
// import TopNav from "@/components/TopNav"; // ✅ Import it here

// export default function RootLayout({ children }) {

//   return (
//     <html lang="en">
//       <body className="antialiased">
//         <div className="flex min-h-screen">
//           <Sidebar />
//           <div className="flex-1 flex flex-col">
//             <TopNav /> 
//             <main className="flex-1 p-4">{children}</main>
//           </div>
//         </div>
//       </body>
//     </html>
//   );
// }

// layout.js
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="h-screen overflow-hidden">
        <div className="flex h-full">
          <Sidebar />
          <main className="flex-1 h-full overflow-auto">{children}</main>
        </div>
      </body>
    </html>
  );
}
